### ISSUE TITLE
Suggestion for `isdown`

### ISSUE THREAD

**Issue by mingyee2** [rostok/ubichr#13]
The current behaviour is prioritise an explicitly given argument, and if none is given, to use the selection. It might be useful to, if there is no selection either, use the URL (or domain) of the current tab, since it seems sensible that, if I visit a website that does not seem to be loading, my first instinct might be to open UbiChr and call isdown, and it is a bit more clunky to have to have copied the URL first from the address bar.

**Comment by rostok** [comment]
think it should be fixed now as the first line added http:// prefix if no argument was given

**Comment by rostok** [comment]
oh, btw - the common way to apply a quick fix for commands is to copy their code with `gist` and paste into editor with changes. this should overwrite builtin code.

**Comment by mingyee2** [comment]
That’s a good point, but I figured you might like to import the functionality into the main plugin :)
