### ISSUE TITLE
Last character sometimes deletes when closing and reopening UbiChr command window

### ISSUE THREAD

**Issue by mingyee2** [rostok/ubichr#14]
Often (but not consistently), when I close the UbiChr window, if I open it again with Ctrl+Space, the last command I inputted is retained (which is fine), _except for the last character of the input._ This does not happen all the time, but pretty often; so far I have not been able to figure out the pattern, but I thought I should bring it to your attention in case you are able to reproduce it and figure out what is going on. I noticed it most often when doing testing or debugging for my own commands.

**Comment by rostok** [comment]
it never occured for me but i think it is possible as command is saved on global keydown event so there is a possibility that input is not yet updated. will look into that.

**Comment by mingyee2** [comment]
I just noticed today that it sometimes is not the last character that is missing, but the last character I inputted (which could be in the middle), so it probably is some key listener not firing properly, as you hypothesize

**Comment by rostok** [comment]
in 0.1.0.61 command is saved on input event instead of key down, should fix this issue.
