### ISSUE TITLE
Command Line Syntax for Ubiquity

### ISSUE THREAD

**Issue by Svalorzen** [rostok/ubichr#5]
Following our discussion via mail, I thought of making an issue so more people can contribute their ideas and we can also try to decide what the future of the project will be.

The thing is that the old paradigm used by Ubiquity (the natural language ideas) is probably not really useful anymore, and simply complicates things.

In addition, it makes very hard to devise commands that can become composable, such for example being able to grep in a webpage and pipe the result to a search/map command.

Thus, an idea would be to allow commands to explicitly list options (instead of relying on the hardcoded ones present in the old Ubiquity), and to allow commands to send/receive tagged data to each other in order to pass data to other commands.

This basically contains two problems: how to handle the parsing of a command, and what output it should generate, and how to handle the passing of data from a command to another.

For the first problem, me and @rostok had a brief discussion about what the output of a parse could look like. 

For an hypothetical "directions" command, defined with options "from", "to", and "time == now" (default), the output of a parse of the line

    directions test1 -from 'Sao Paulo' test2 -to 'London' -to 'Milan' test3 -random test4

Would be:

        var directObj = {
            text: “directions test1 -from 'Sao Paulo' test2 -to 'London' -to 'Milan' test3 -random test4”,
            command: "directions",
            input: "test1 test2 test3 -random test4", // random was not a defined flag so counts as input. all inputs around the text are merged
            from: “Sao Paulo”,
            to: [“London”, "Milan"],
            time: "now", // default value
            args: [“from”, “to”, “time”] // time is last since defaulted
        };

This object would then be passed to the code of the command, which would do its job. Options could also be specified with types, so that if a type does not match (number, string, list), the command parsing fails.

About the ability to pipe this data to another command, it becomes harder, because the other command would need to be able to interpret the input data. This can quickly become a N^2 problem unless we can devise a common passing scheme.

An idea for this could be to allow the user to manually redirect the fields from a command to another. So maybe if there was a command to find a restaurant, and we wanted directions to that, we could do:

    yelp restaurant | directions -from here -to {location}

Where the yelp command returned a structure containing a `location` field. The user would need a way to inspect the output structure of a command when piping in order to know how to mesh commands together.

**Comment by rostok** [comment]
closing as this wont be implemented
