### ISSUE TITLE
custom commands

### ISSUE THREAD

**Issue by ledemon** [rostok/ubichr#9]
Add custom command (from command editor) to context menu bug the ubiquitwe context menu list.
firefox 69.0.1, windows 10, x64

**Comment by rostok** [comment]
Could you please elaborate on this issue. There was never context menu support in ubichr and I am not sure if this is a bug issue or feature request. In case of latter please describe desired effect.

**Comment by ledemon** [comment]
sorry, my mistake, I try to open a issue in ubiquitywe but is a fork of you work and I end here thinking maybe you owns both
